/*
 *    MCreator note:
 *
 *    If you lock base mod element files, you can edit this file and the proxy files
 *    and they won't get overwritten. If you change your mod package or modid, you
 *    need to apply these changes to this file MANUALLY.
 *
 *    Settings in @Mod annotation WON'T be changed in case of the base mod element
 *    files lock too, so you need to set them manually here in such case.
 *
 *    Keep the SirenHeadModModElements object in this class and all calls to this object
 *    INTACT in order to preserve functionality of mod elements generated by MCreator.
 *
 *    If you do not lock base mod element files in Workspace settings, this file
 *    will be REGENERATED on each build.
 *
 */
package net.mcreator.sirenhead;

import net.mcreator.sirenhead.HunterBow.BowItemModelsProperties;
import net.mcreator.sirenhead.init.SirenHeadRegistry;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

import net.minecraftforge.fml.network.simple.SimpleChannel;
import net.minecraftforge.fml.network.NetworkRegistry;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.common.MinecraftForge;

import net.minecraft.util.ResourceLocation;

@Mod("siren_head_mod")
public class SirenHeadModMod {
	public static final Logger LOGGER = LogManager.getLogger(SirenHeadModMod.class);
	private static final String PROTOCOL_VERSION = "1";
	public static final String MOD_ID = "siren_head_mod";
	public SirenHeadModMod() {
		SirenHeadRegistry.init();
		FMLJavaModLoadingContext.get().getModEventBus().register(this);
		FMLJavaModLoadingContext.get().getModEventBus().addListener(this::setup);
	}

	@SuppressWarnings("deprecation")
	private void setup(final FMLCommonSetupEvent event) {
		DeferredWorkQueue.runLater(() -> {
			MinecraftForge.EVENT_BUS.register(new BowItemModelsProperties());
		});
	}
}

